dist: xenial
sudo: true

language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - CC=gcc-4.9 CXX=g++-4.9

before_install:
  - python -m pip install -U pip
  - python -m pip install --progress-bar off numpy
  - python -m pip install --progress-bar off pybind11
  - python -m pip install --progress-bar off torch

script:
  - CC=$CXX python setup.py install
  - cd /tmp 
  - python -m prob_phoc.test
  - cd -

notifications:
  email:
      on_success: change
      on_failure: always
