language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - CC=g++

before_install:
  - easy_install -q -U pip
  - pip install --progress-bar off numpy
  - pip install --progress-bar off scipy
  - pip install --progress-bar off torch
  - pip install --progress-bar off cffi

script:
  - python setup.py install
  - cd $HOME
  - python -m prob_phoc.phoc_test

notifications:
  email:
      on_success: change
      on_failure: always
